Adds steel accumulation in compareScenario2
pik-piam/remind2 pull request #273
Opened 2022-05-31 08:57 UTC by mellamoSimon

Adds plots for the evolution of the steel stock to compareScenario2. Requires updates to `mrremind` in this [PR](https://github.com/pik-piam/mrremind/pull/271)

2022-05-31 09:26 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q requested changes

2022-05-31 09:33 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q requested changes

2022-05-31 09:45 UTC, chroetz commented
You do not need to use `:=`  or `!!sym("...")` for your code to work, I think. Just replace `!!sym("XXX")` by `XXX` . Then all `:=` can be replaces by `=`. This makes the style of the code more in line with the style used elsewhere in cs2

2022-06-01 10:28 UTC, mellamoSimon commented on inst/markdown/compareScenarios2/cs2_06_energy_services.Rmd
> +showLinePlots(stock, "Production|Industry|Steel|Accumulated Production", mainReg = "World")
done, thank you!

2022-06-01 12:45 UTC, fbenke-pik approved these changes

2022-06-01 15:21 UTC, chroetz approved these changes

2022-06-01 15:32 UTC, merged