Calib
pik-piam/remind2 pull request #292
Opened 2022-06-24 15:03 UTC by fbenke-pik

2022-06-27 08:11 UTC, chroetz requested changes

2022-06-27 09:11 UTC, fbenke-pik commented on R/checkVsCalibData.R
> +  yamlParams <- c(list(gdx = normalizePath(gdx, mustWork = TRUE)))
no, they were just a leftover, i dont need the `...` argument. hence, removing the `c()`

2022-06-27 09:13 UTC, fbenke-pik commented on inst/markdown/checkVsCalibData/rc_main.Rmd
> +min.absdev <- 1e-1
for now, we don't need to make them adjustable. they are constants.

2022-06-27 10:19 UTC, fbenke-pik commented on inst/markdown/checkVsCalibData/rc_main.Rmd
> +  message = FALSE,
has been adjusted

2022-06-27 10:20 UTC, fbenke-pik commented on inst/markdown/checkVsCalibData/rc_main.Rmd
> +  as.quitte(q.calibration) %>% select(region, variable = all_in, period, value) %>% mutate(model := "Calibration"),
fixed

2022-06-28 09:36 UTC, fschreyer approved these changes

2022-06-28 10:15 UTC, merged