average LCO for carbon capture and cdr technologies
pik-piam/remind2 pull request #540
Opened 2024-02-16 17:47 UTC by tabeado

**Cost per tCO2:**
- for **all carbon capturing technologies that enter the CCUS-chain**: all cost are distributed across the captured co2 (thus output=cco2), only CTS cost are distributed across the share thereof that is injected (thus output=ico2). The total cost are calculated accordingly for both captured co2 and for injected co2. There is no distinction between fossil, biogenic, and atmospheric options, as this would blow up the calculation.
- for **CDR technologies that do not enter the CCUS-chain**: introduction of the entity "sco2 = stored CO2". Currently only Enhanced Weathering, but already prepared to also accomodate biochar (&hopefully OAE) without too many changes.
- backwards compatibility: Script works also for runs prior to refarctoring of the CDR module (Nov 2023). However, the fuel demand for dac & enhanced weathering would require significant addition of code which would not be worth it. These cost are thus (falsely) returned to be 0.
- Note that the *all* of the technologies' cost are accounted to CO2. Thus it is *not* the additional cost incurred through the CC for the pe2se techs. We might consider adding revenue accrued to this calculation in the future.
 
**Further changes:**
- Make **discount rate** for average LCO explicit & align with marginal LCO calculation (from 0.06 to 0.05)
- Correct the **distribution of ccsinje cost** for teCCS and add **ccs-cost incl. adjustment cost**
- Add **secondary fuel cost** for all technologies
- Add **total cost** without & with all adjustment costs also for pe2se technologies
- Use same name for injected co2 (ico2) & sector (carbon management) for average and marginal LCO

2024-03-01 08:56 UTC, tabeado commented
test results are here: /p/tmp/tabeado/remind2_clean/reportLCOE_enhancedWeathering

2024-03-05 16:11 UTC, fschreyer requested changes
I mainly looked at the small change that also affected the energy system technologies. I only had a superficial look at the carbon management part and did not spot anything in particular.

2024-04-03 07:26 UTC, tabeado commented
@amerfort and @katarkow , could you have a look at the CDR-part please?

2024-04-03 07:33 UTC, tabeado commented on R/reportLCOE.R
> +                       paste0("LCOE|average|",pe2se$all_enty1,"|",pe2se$all_te, "|supply-side","|Total Cost")),
Thank you for spotting this! I included the cost now

2024-04-23 09:37 UTC, amerfort approved these changes
Thanks for taking care of this! Numbers seem very reasonable.
In a next step, we should probably extract the CO2 capture part from the energy output. A first idea would be to subtract the price of the output fuel from the total LCO-CC. Let's discuss :)

2024-04-23 14:35 UTC, fschreyer approved these changes

2024-04-23 14:36 UTC, merged