clean up plotLCOE.R
pik-piam/remind2 pull request #664
Opened 2024-10-07 12:48 UTC by fbenke-pik

2024-10-21 14:18 UTC, orichters commented on R/reportLCOE.R
> +#' It is used to guarantee consistency for Moving Avg prices before cm_startyear
Really prices here, or is that copied from reportPrices?

2024-10-30 14:36 UTC, robertpietzcker commented on R/reportCapacity.R
> +
I would add a comment here to explain the next lines, something like: 

## apply "modifyInvestmentVariables to shift from the model-internal time coverage (deltacap and investment variables for step t represent the average of the years from t-4years to t) to the general convention for the reporting template (all variables represent the average of the years from   t-2.5years to t+2.5years)

2024-10-30 14:40 UTC, robertpietzcker commented on R/reportEnergyInvestment.R
> +  if (!is.null(gdx_ref)) {
I would add a comment here to explain the next lines, something like: 

apply "modifyInvestmentVariables" to shift from the model-internal time coverage (deltacap and investment variables for step t represent the average of the years from t-4years to t) to the general convention for the reporting template (all variables represent the average of the years from   t-2.5years to t+2.5years)

2024-10-30 14:41 UTC, robertpietzcker commented on R/reportLCOE.R
> +
I would add a comment here to explain the next lines, something like: 

apply "modifyInvestmentVariables" to shift from the model-internal time coverage (deltacap and investment variables for step t represent the average of the years from t-4years to t) to the general convention for the reporting template (all variables represent the average of the years from   t-2.5years to t+2.5years)

2024-10-30 15:35 UTC, robertpietzcker commented on R/modifyInvestmentVariables.R
> +#' Timesteps for investment variables represent a different year range than
I would reformulate slightly:

Years represented by investment variables in the energy system (vm_deltacap, vm_xxx) {please insert all variables this is applied to} are different than in the normal reporting convention. In the current REMIND version, vm_deltacap(t) represents the average of the years t-4years...t (for 5 year time steps), while in the general reporting convention it represents the average of t-2.5years to t+2.5years.

2024-10-30 15:36 UTC, robertpietzcker commented on R/reportLCOE.R
> +    ## Total direct Investment Cost in Timestep
I would add a comment here to explain the next lines, something like:

apply "modifyInvestmentVariables" to shift from the model-internal time coverage (deltacap and investment variables for step t represent the average of the years from t-4years to t) to the general convention for the reporting template (all variables represent the average of the years from t-2.5years to t+2.5years)

2024-10-30 15:40 UTC, robertpietzcker approved these changes
thanks a lot for implementing it!

there are many formatting changes that I can't comment on - it seems that the new convention is to add an empty space between function inputs? I like it, but I think if this is now the general formatting it would be good to communicate it as such in the next 1-3 REMIND meetings (to reach all people who are missing in one meeting)

On the concrete shift changes: I made some proposals to make the comments more concrete/ add a comment each time that modifyInvestmentVariables is applied.

I can't comment on the actual calculations, my R is too limited to understand if it was applied correctly - but I trust you :-)

2024-11-04 09:55 UTC, fbenke-pik commented
> there are many formatting changes that I can't comment on - it seems that the new convention is to add an empty space between function inputs? I like it, but I think if this is now the general formatting it would be good to communicate it as such in the next 1-3 REMIND meetings (to reach all people who are missing in one meeting)

The formatting changes are not mandatory (they wont stop you from finishing buildLibrary). I just applied the auto formatting and fixed indentation. The former can be done by using `lucode2::autoFormat(PATH_TO_FILE)`, the latter is done in RStudio by entering Ctrl + I. Both are automatic steps that improve readability a bit, so they don't hurt, but are optional. Sorry for mixing them with the other changes, as it makes it harder to check the PR, but I did not make any changes other than formatting on existing code in the report functions, so focusing on the new functions and the new code blocks is sufficient.

2024-11-04 10:03 UTC, fbenke-pik commented
> I can't comment on the actual calculations, my R is too limited to understand if it was applied correctly - but I trust you :-)

Take a look at the before/after comparison and check if you spot some irregularities
Differences in convGDX2MIF can be found here: https://cloud.pik-potsdam.de/index.php/f/22517932
Differences in convGDX2MIF_LCOE can be found here: https://cloud.pik-potsdam.de/index.php/f/22560628

2024-11-04 10:10 UTC, robertpietzcker commented
> Differences in convGDX2MIF_LCOE can be found here: https://cloud.pik-potsdam.de/index.php/f/22560628

thanks for reminding me about this again. 

The capacity and energy investment variables look fine; the LCOE variables don't. 

the average LCOE is calculated based on the total output of the technology divided by the total costs incurred until that moment. 
with the new shift of investments by half a time step in the reporting, this means the model sees already lots of investments while not actually producing any energy, leading to hugely overblown numbers for technologies that are growing. 

I would propose to revert all the changes in the LCOE script.

or what do you say, @fschreyer ?

2024-11-05 09:08 UTC, fschreyer requested changes
Thanks, Falk! That's great. I checked the ``modifyInvestmentVariables`` function with an example GDX and the key part looks all correct to me. I made the comments a bit more verbose and opened a PR to your branch. 

I agree with Robert that this function should not be applied in the reportLCOE function. Here, the current model definition of investments over t-4 to t of timestep t is actually what we want in the calculation of average LCOE.

2024-11-05 09:49 UTC, fbenke-pik commented on R/modifyInvestmentVariables.R
> +    x[joinedRegions, fixedYears, joinedNames] <- ref[joinedRegions, fixedYears, joinedNames]
Ok, I can implement it that way. It was written like this, as I adapted the logic from Oliver's implementation for Prices.

2024-11-05 15:10 UTC, merged

2024-11-06 10:03 UTC, robertpietzcker commented on R/reportCapitalStock.R
> +    tmp2 <- mbind(tmp2, setNames(dimSums(vm_deltaCap[, , "apcarDiEffH2T"], dim = c(3.1, 3.2)), "Services and Products|Transport|non-LDV|Sales|apcarDiEffH2T (arbitrary unit)"))
yes, I agree